services:
  testdb:
    hostname: database
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/${POSTGRES_DATABASE}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: